import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#121212' }, flex: { flex: 1 }, scrollView: { flex: 1 }, scrollContent: { padding: 10, paddingBottom: 40 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 10, paddingVertical: 6, gap: 8 }, headerTitle: { fontSize: 16, fontWeight: 'bold', color: '#fff' },
  userHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 8, paddingHorizontal: 4, marginBottom: 8 },
  userHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  userBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1a1a1a', paddingVertical: 6, paddingHorizontal: 10, borderRadius: 16, gap: 6 },
  tierDot: { width: 8, height: 8, borderRadius: 4 },
  userBadgeText: { fontSize: 11, color: '#fff', fontWeight: '500', textTransform: 'capitalize' },
  loginBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(76,175,80,0.15)', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 16, gap: 6, borderWidth: 1, borderColor: '#4CAF50' },
  loginBadgeText: { fontSize: 12, color: '#4CAF50', fontWeight: '600' },
  maxElementsHint: { fontSize: 10, color: '#888', fontWeight: '400' },
  section: { backgroundColor: '#1a1a1a', borderRadius: 10, padding: 10, marginBottom: 8 }, sectionTitle: { fontSize: 13, fontWeight: '600', color: '#fff', marginBottom: 6 }, sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  rowSpaced: { flexDirection: 'row', alignItems: 'flex-end', gap: 6 },
  inputLabel: { fontSize: 10, color: '#aaa', marginBottom: 3 }, input: { backgroundColor: '#252525', borderRadius: 6, padding: 8, fontSize: 13, color: '#fff', borderWidth: 1, borderColor: '#333' },
  unitToggle: { flexDirection: 'row', backgroundColor: '#252525', borderRadius: 6, overflow: 'hidden', marginLeft: 4 }, unitBtn: { paddingVertical: 8, paddingHorizontal: 8 }, unitBtnActive: { backgroundColor: '#4CAF50' }, unitBtnText: { fontSize: 11, color: '#888' }, unitBtnTextActive: { color: '#fff', fontWeight: '600' },
  dropdownContainer: { marginBottom: 6, zIndex: 1000, position: 'relative' }, dropdownButton: { backgroundColor: '#252525', borderRadius: 6, padding: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#333' }, dropdownButtonText: { fontSize: 12, color: '#fff' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalDropdown: { backgroundColor: '#1e1e1e', borderRadius: 12, width: '85%', maxHeight: '70%', padding: 8, borderWidth: 1, borderColor: '#444' },
  modalDropdownTitle: { fontSize: 14, fontWeight: '700', color: '#fff', textAlign: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#333' },
  modalDropdownItem: { padding: 14, borderBottomWidth: 1, borderBottomColor: '#222', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalDropdownItemSelected: { backgroundColor: '#1a3a1a' },
  modalDropdownItemText: { fontSize: 15, color: '#ccc' },
  modalDropdownItemTextSelected: { color: '#4CAF50', fontWeight: '600' },
  elementCard: { backgroundColor: '#222', borderRadius: 6, padding: 6, marginTop: 4, borderLeftWidth: 3 }, elementTitle: { fontSize: 11, fontWeight: '600', marginBottom: 4 }, elementRow: { flexDirection: 'row', gap: 6 }, elementField: { flex: 1 }, elementLabel: { fontSize: 9, color: '#888', marginBottom: 2 }, elementInput: { backgroundColor: '#1a1a1a', borderRadius: 4, padding: 6, fontSize: 12, color: '#fff', borderWidth: 1, borderColor: '#333' },
  taperSection: { backgroundColor: '#222', borderRadius: 6, padding: 6, marginTop: 4 }, taperSectionTitle: { fontSize: 10, color: '#E91E63', fontWeight: '600', marginBottom: 4 },
  orientationToggle: { flexDirection: 'row', gap: 6, marginVertical: 6 }, orientBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#252525', borderRadius: 6, padding: 8, gap: 4 }, orientBtnActive: { backgroundColor: '#9C27B0' }, orientBtnText: { fontSize: 11, color: '#888' }, orientBtnTextActive: { color: '#fff', fontWeight: '600' },
  autoTuneBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FF9800', borderRadius: 6, paddingVertical: 6, paddingHorizontal: 10, gap: 4 }, autoTuneBtnText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  resultsSection: { marginTop: 4 },
  bonusCard: { backgroundColor: '#1a1a1a', borderRadius: 6, padding: 6, marginBottom: 4 }, bonusText: { fontSize: 11, color: '#ccc' },
  swrContainer: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 8, marginBottom: 6, alignItems: 'center' }, swrTitle: { fontSize: 12, fontWeight: '600', color: '#fff', marginBottom: 4 }, swrLegend: { flexDirection: 'row', gap: 12, marginTop: 4 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 }, legendColor: { width: 10, height: 10, borderRadius: 2 }, legendText: { fontSize: 9, color: '#888' },
  mainResults: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginBottom: 6 }, mainResultItem: { alignItems: 'center' }, mainResultLabel: { fontSize: 9, color: '#888', marginBottom: 2 }, mainResultValue: { fontSize: 16, fontWeight: 'bold', color: '#fff' },
  secondaryResults: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', backgroundColor: '#1a1a1a', borderRadius: 8, padding: 8, marginBottom: 6 }, secondaryResultItem: { width: '48%', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }, secondaryLabel: { fontSize: 10, color: '#888' }, secondaryValue: { fontSize: 10, color: '#fff', fontWeight: '500' },
  polarContainer: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 8, alignItems: 'center' }, polarTitle: { fontSize: 12, fontWeight: '600', color: '#fff', marginBottom: 6 },
  taperHint: { fontSize: 10, color: '#E91E63', marginBottom: 8, fontStyle: 'italic' },
  inputDisabled: { backgroundColor: '#1a1a1a', color: '#666', borderColor: '#222' },
  reflectorToggle: { flexDirection: 'row', flex: 1, gap: 6 },
  reflectorBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#252525', borderRadius: 6, paddingVertical: 6, paddingHorizontal: 8, gap: 4 },
  reflectorBtnActive: { backgroundColor: '#4CAF50' },
  reflectorBtnText: { fontSize: 10, color: '#888' },
  reflectorBtnTextActive: { color: '#fff', fontWeight: '600' },
  optimizeHeightBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#2196F3', borderRadius: 6, paddingVertical: 8, paddingHorizontal: 12, marginTop: 8, gap: 6 },
  optimizeHeightBtnText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  heightOptResult: { backgroundColor: '#1f3d1f', borderRadius: 8, padding: 10, marginTop: 8, borderWidth: 1, borderColor: '#4CAF50' },
  heightOptTitle: { fontSize: 11, color: '#4CAF50', fontWeight: '600', textAlign: 'center', marginBottom: 6 },
  heightOptRow: { flexDirection: 'row', justifyContent: 'space-around' },
  heightOptItem: { alignItems: 'center' },
  heightOptLabel: { fontSize: 10, color: '#888' },
  heightOptValue: { fontSize: 18, fontWeight: 'bold', color: '#4CAF50' },
  saveLoadButtons: { flexDirection: 'row', gap: 6 },
  saveBtn: { backgroundColor: '#4CAF50', borderRadius: 6, padding: 8 },
  loadBtn: { backgroundColor: '#2196F3', borderRadius: 6, padding: 8 },
  modalContent: { backgroundColor: '#1a1a1a', borderRadius: 12, padding: 16, width: '100%', maxWidth: 360 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#fff' },
  modalLabel: { fontSize: 12, color: '#888', marginBottom: 6 },
  modalInput: { backgroundColor: '#252525', borderRadius: 8, padding: 12, fontSize: 14, color: '#fff', borderWidth: 1, borderColor: '#333', marginBottom: 12 },
  modalInfo: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 16 },
  modalInfoText: { fontSize: 11, color: '#888', flex: 1 },
  modalSaveBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#4CAF50', borderRadius: 8, paddingVertical: 12, gap: 8 },
  modalSaveBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  emptyDesigns: { alignItems: 'center', paddingVertical: 32 },
  emptyDesignsText: { fontSize: 14, color: '#666', marginTop: 12 },
  emptyDesignsHint: { fontSize: 11, color: '#555', marginTop: 4 },
  designItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#252525', borderRadius: 8, marginBottom: 8 },
  designItemContent: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12 },
  designItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  designItemName: { fontSize: 13, color: '#fff', fontWeight: '500' },
  designItemDate: { fontSize: 10, color: '#666', marginTop: 2 },
  designDeleteBtn: { padding: 12, borderLeftWidth: 1, borderLeftColor: '#333' },
  patternDataSection: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginTop: 6 },
  patternDataTitle: { fontSize: 12, fontWeight: '600', color: '#4CAF50', marginBottom: 8 },
  patternDataGrid: { gap: 6 },
  patternDataRow: { flexDirection: 'row', justifyContent: 'space-between' },
  patternDataCell: { flex: 1, alignItems: 'center', backgroundColor: '#252525', borderRadius: 6, padding: 8, marginHorizontal: 2 },
  patternAngle: { fontSize: 9, color: '#888', marginBottom: 2 },
  patternValue: { fontSize: 14, fontWeight: 'bold', color: '#fff' },
  beamwidthIndicator: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#333' },
  beamwidthItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  beamwidthLabel: { fontSize: 9, color: '#888' },
  beamwidthValue: { fontSize: 11, fontWeight: '600', color: '#fff' },
  performanceCard: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginTop: 6 },
  performanceTitle: { fontSize: 12, fontWeight: '600', color: '#FF9800', marginBottom: 10 },
  performanceGrid: { gap: 8 },
  perfItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  perfLabel: { fontSize: 10, color: '#888', width: 60 },
  perfBar: { flex: 1, height: 8, backgroundColor: '#252525', borderRadius: 4, overflow: 'hidden' },
  perfBarFill: { height: '100%', borderRadius: 4 },
  perfValue: { fontSize: 11, fontWeight: '600', color: '#fff', width: 55, textAlign: 'right' },
  powerConversion: { marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#333' },
  powerTitle: { fontSize: 10, color: '#888', marginBottom: 6, textAlign: 'center' },
  powerRow: { flexDirection: 'row', justifyContent: 'space-around' },
  powerItem: { alignItems: 'center' },
  powerLabel: { fontSize: 9, color: '#666' },
  powerValue: { fontSize: 14, fontWeight: 'bold', color: '#4CAF50' },
  heightPerfCard: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginTop: 6 },
  heightPerfTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  heightPerfTitle: { fontSize: 12, fontWeight: '600', color: '#00BCD4' },
  heightPerfScrollView: { maxHeight: 200 },
  heightPerfTable: { borderRadius: 6, overflow: 'hidden' },
  heightPerfHeader: { flexDirection: 'row', backgroundColor: '#252525', paddingVertical: 6, paddingHorizontal: 4 },
  heightPerfHeaderText: { flex: 1, fontSize: 9, fontWeight: '600', color: '#888', textAlign: 'center' },
  heightPerfRow: { flexDirection: 'row', paddingVertical: 6, paddingHorizontal: 4, borderBottomWidth: 1, borderBottomColor: '#252525' },
  heightPerfRowOptimal: { backgroundColor: 'rgba(76,175,80,0.2)' },
  heightPerfCell: { flex: 1, fontSize: 10, color: '#ccc', textAlign: 'center' },
  heightPerfCellOptimal: { color: '#4CAF50', fontWeight: '600' },
  heightPerfNote: { fontSize: 9, color: '#4CAF50', marginTop: 8, textAlign: 'center', fontStyle: 'italic' },
  fullTableTitle: { fontSize: 10, color: '#888', marginTop: 12, marginBottom: 4 },
  top5Section: { backgroundColor: '#252525', borderRadius: 8, padding: 10, marginBottom: 10 },
  top5Title: { fontSize: 11, fontWeight: '600', color: '#FFD700', marginBottom: 8 },
  top5Table: { borderRadius: 6, overflow: 'hidden' },
  top5Header: { flexDirection: 'row', backgroundColor: '#333', paddingVertical: 6, paddingHorizontal: 4 },
  top5HeaderText: { flex: 1, fontSize: 9, fontWeight: '600', color: '#888', textAlign: 'center' },
  top5Row: { flexDirection: 'row', paddingVertical: 8, paddingHorizontal: 4, borderBottomWidth: 1, borderBottomColor: '#333' },
  top5RowBest: { backgroundColor: 'rgba(255,215,0,0.15)' },
  top5Cell: { flex: 1, fontSize: 11, color: '#ccc', textAlign: 'center' },
  top5Rank: { fontWeight: '600' },
  top5CellBest: { color: '#FFD700', fontWeight: 'bold' },
  exportBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#00BCD4', borderRadius: 4, paddingVertical: 4, paddingHorizontal: 8, gap: 4 },
  exportBtnText: { fontSize: 10, color: '#fff', fontWeight: '600' },
  exportAllBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#9C27B0', borderRadius: 8, paddingVertical: 12, marginTop: 10, gap: 8 },
  exportAllBtnText: { fontSize: 13, color: '#fff', fontWeight: '600' },
  reflectedPowerCard: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginTop: 6 },
  reflectedPowerTitle: { fontSize: 12, fontWeight: '600', color: '#f44336', marginBottom: 10 },
  reflectedPowerGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  reflectedPowerItem: { flex: 1, alignItems: 'center' },
  reflectedPowerLabel: { fontSize: 9, color: '#888', marginBottom: 2 },
  reflectedPowerValue: { fontSize: 13, fontWeight: 'bold', color: '#fff' },
  reflectedPowerTable: { backgroundColor: '#252525', borderRadius: 6, overflow: 'hidden', marginBottom: 10 },
  reflectedPowerTableHeader: { flexDirection: 'row', backgroundColor: '#333', paddingVertical: 6 },
  reflectedPowerTableHeaderText: { flex: 1, fontSize: 10, fontWeight: '600', color: '#888', textAlign: 'center' },
  reflectedPowerTableRow: { flexDirection: 'row', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#333' },
  reflectedPowerTableCell: { flex: 1, fontSize: 12, color: '#fff', textAlign: 'center', fontWeight: '500' },
  impedanceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 8, borderTopWidth: 1, borderTopColor: '#333' },
  impedanceLabel: { fontSize: 10, color: '#888' },
  impedanceValue: { fontSize: 12, fontWeight: '600', color: '#FF9800' },
  groundTypeSelector: { flexDirection: 'row', gap: 8, marginTop: 4 },
  groundTypeBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: '#252525', borderRadius: 8, padding: 10, borderWidth: 1, borderColor: '#333' },
  groundTypeBtnActive: { backgroundColor: '#8BC34A', borderColor: '#8BC34A' },
  groundTypeBtnText: { fontSize: 11, color: '#888' },
  groundTypeBtnTextActive: { color: '#fff', fontWeight: '600' },
  groundRadialHint: { fontSize: 9, color: '#666', marginTop: 8, textAlign: 'center' },
  groundRadialInfo: { backgroundColor: '#252525', borderRadius: 6, padding: 8, marginTop: 8 },
  groundRadialInfoText: { fontSize: 10, color: '#ccc', marginBottom: 2 },
  takeoffCard: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginTop: 6 },
  takeoffHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  takeoffTitle: { fontSize: 12, fontWeight: '600', color: '#FF5722' },
  takeoffContent: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 8 },
  takeoffValue: { fontSize: 28, fontWeight: 'bold', color: '#fff' },
  takeoffDesc: { fontSize: 11, color: '#4CAF50', fontWeight: '500' },
  takeoffBar: { height: 8, backgroundColor: '#252525', borderRadius: 4, overflow: 'hidden' },
  takeoffBarFill: { height: '100%', backgroundColor: '#FF5722', borderRadius: 4 },
  takeoffScale: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  takeoffScaleText: { fontSize: 8, color: '#666' },
  lockHint: { fontSize: 10, color: '#888', marginBottom: 12 },
  lockRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#1a1a1a', borderRadius: 10, padding: 12 },
  lockLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  lockLabelContainer: { flex: 1 },
  lockLabel: { fontSize: 13, fontWeight: '600', color: '#fff' },
  lockDesc: { fontSize: 10, color: '#888', marginTop: 2 },
  lockInputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#252525', borderRadius: 8, paddingHorizontal: 8, borderWidth: 1, borderColor: '#FF9800' },
  lockInput: { width: 60, padding: 8, fontSize: 14, color: '#fff', textAlign: 'center' },
  lockInputUnit: { fontSize: 12, color: '#888' },
  lockBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(33,150,243,0.2)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  lockBadgeText: { fontSize: 10, color: '#2196F3', fontWeight: '500' },
  currentBoomInfo: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 8, paddingLeft: 4 },
  currentBoomText: { fontSize: 10, color: '#888' },
  boomWarning: { fontSize: 10, color: '#f44336', fontWeight: '600' },
  elevationContainer: { backgroundColor: '#1a1a1a', borderRadius: 12, padding: 12, marginVertical: 10, alignItems: 'center' },
  elevationTitle: { fontSize: 12, fontWeight: '600', color: '#FF5722', marginBottom: 8, textAlign: 'center' },
  elevationLegend: { marginTop: 8 },
  elevationLegendText: { fontSize: 11, color: '#4CAF50', fontWeight: '500' },
  elevationLegendRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  elevationLegendDot: { width: 8, height: 8, borderRadius: 4 },
  smithContainer: { backgroundColor: '#1a1a1a', borderRadius: 12, padding: 12, marginVertical: 10, alignItems: 'center' },
  smithTitle: { fontSize: 12, fontWeight: '600', color: '#00BCD4', marginBottom: 8, textAlign: 'center' },
  smithReadout: { width: '100%', marginTop: 10, backgroundColor: '#111', borderRadius: 8, padding: 10 },
  smithReadoutRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  smithReadoutItem: { flex: 1, alignItems: 'center' },
  smithReadoutLabel: { fontSize: 9, color: '#666', marginBottom: 2 },
  smithReadoutValue: { fontSize: 12, fontWeight: '700', color: '#00BCD4' },
  smithBandEdges: { marginTop: 6, borderTopWidth: 1, borderTopColor: '#222', paddingTop: 6 },
  smithBandEdgeText: { fontSize: 9, color: '#888', marginBottom: 2 },
  orientationSection: { marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#333' },
  orientationLabel: { fontSize: 10, color: '#888', marginBottom: 6 },
  orientationBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, backgroundColor: '#252525', borderRadius: 8, paddingVertical: 10, borderWidth: 1, borderColor: '#333' },
  orientationBtnActive: { backgroundColor: '#2196F3', borderColor: '#2196F3' },
  orientationIcon: { fontSize: 14, color: '#888', fontWeight: 'bold' },
  orientationBtnText: { fontSize: 11, color: '#888' },
  orientationBtnTextActive: { color: '#fff', fontWeight: '600' },
  heightSortSection: { marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#333' },
  heightSortLabel: { fontSize: 10, color: '#888', marginBottom: 6 },
  heightSortOptions: { flexDirection: 'row', gap: 6 },
  heightSortBtn: { paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#252525', borderRadius: 6, borderWidth: 1, borderColor: '#333' },
  heightSortBtnActive: { backgroundColor: '#4CAF50', borderColor: '#4CAF50' },
  heightSortBtnText: { fontSize: 10, color: '#888' },
  heightSortBtnTextActive: { color: '#fff', fontWeight: '600' },
  sortedHeightsList: { marginTop: 12 },
  sortedHeightsTitle: { fontSize: 10, color: '#888', marginBottom: 6 },
  sortedHeightsHeader: { flexDirection: 'row', backgroundColor: '#333', borderRadius: 4, paddingVertical: 6, paddingHorizontal: 4, marginBottom: 4 },
  sortedHeightsCell: { fontSize: 9, color: '#888', textAlign: 'center', fontWeight: '600' },
  sortedHeightsRow: { flexDirection: 'row', paddingVertical: 6, paddingHorizontal: 4, borderBottomWidth: 1, borderBottomColor: '#333' },
  sortedHeightsRowTop: { backgroundColor: 'rgba(76,175,80,0.15)' },
  sortedHeightsCellValue: { fontSize: 10, color: '#ccc' },
  resultCard: { backgroundColor: '#1a1a1a', borderRadius: 8, padding: 10, marginBottom: 4, borderLeftWidth: 3 },
  resultHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  resultTitle: { fontSize: 11, color: '#888', fontWeight: '500' },
  resultValue: { fontSize: 18, fontWeight: 'bold' },
  resultDescription: { fontSize: 10, color: '#888', marginTop: 2 },
});
