export interface ElementDimension { element_type: 'reflector' | 'driven' | 'director'; length: string; diameter: string; position: string; }
export interface TaperSection { length: string; start_diameter: string; end_diameter: string; }
export interface TaperConfig { enabled: boolean; num_tapers: number; center_length: string; sections: TaperSection[]; }
export interface CoronaBallConfig { enabled: boolean; diameter: string; }
export interface StackingConfig { enabled: boolean; orientation: 'vertical' | 'horizontal'; layout: 'line' | 'quad'; num_antennas: number; spacing: string; spacing_unit: 'ft' | 'inches'; h_spacing: string; h_spacing_unit: 'ft' | 'inches'; }
export interface GroundRadialConfig { enabled: boolean; ground_type: string; wire_diameter: string; num_radials: number; }
export interface AntennaInput { num_elements: number; elements: ElementDimension[]; height_from_ground: string; height_unit: 'ft' | 'inches'; boom_diameter: string; boom_unit: 'mm' | 'inches'; band: string; frequency_mhz: string; stacking: StackingConfig; taper: TaperConfig; corona_balls: CoronaBallConfig; ground_radials: GroundRadialConfig; use_reflector: boolean; antenna_orientation: string; dual_active: boolean; dual_selected_beam: 'horizontal' | 'vertical'; feed_type: string; boom_grounded: boolean; boom_mount: 'bonded' | 'insulated' | 'nonconductive'; }
export interface AntennaOutput { swr: number; swr_description: string; fb_ratio: number; fs_ratio: number; beamwidth_h: number; beamwidth_v: number; bandwidth: number; gain_dbi: number; gain_description: string; base_gain_dbi?: number; gain_breakdown?: any; multiplication_factor: number; antenna_efficiency: number; far_field_pattern: any[]; swr_curve: any[]; usable_bandwidth_1_5: number; usable_bandwidth_2_0: number; center_frequency: number; band_info: any; stacking_enabled: boolean; stacking_info?: any; stacked_gain_dbi?: number; stacked_pattern?: any[]; taper_info?: any; corona_info?: any; reflection_coefficient?: number; return_loss_db?: number; mismatch_loss_db?: number; reflected_power_100w?: number; reflected_power_1kw?: number; forward_power_100w?: number; forward_power_1kw?: number; impedance_high?: number; impedance_low?: number; takeoff_angle?: number; takeoff_angle_description?: string; height_performance?: string; ground_radials_info?: any; noise_level?: string; noise_description?: string; feed_type?: string; matching_info?: any; dual_polarity_info?: any; boom_correction_info?: any; wind_load?: any; }
export interface HeightOptResult { optimal_height: number; optimal_swr: number; optimal_gain: number; optimal_fb_ratio: number; heights_tested: { height: number; swr: number; gain: number; fb_ratio: number; takeoff_angle?: number; efficiency?: number; score?: number; }[]; }
